[package]
name = "photon_core"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.9.2"
reed-solomon-erasure = "6.0.0"
clap = { version = "4.5.54", features = ["derive"] }

[dev-dependencies]
proptest = "1.9.0"
criterion = "0.8.1"

[[bench]]
name = "codec_benchmark"
harness = false
